apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-helm
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo-helm
  namespace: podinfo-helm
spec:
  interval: 1m0s
  url: https://stefanprodan.github.io/podinfo